
package GUI;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.EstatisticasVO;
import modelo.SecretariaVO;
import modelo.SetorVO;
import modelo.UsuarioVO;
import servicos.EstatisticasServicos;
import servicos.SecretariaServicos;
import servicos.ServicosFactory;
import servicos.SetorServicos;
import servicos.UsuarioServicos;

/**
 * @author Maikel Maciel Rönnau
 * @version 1.0
 * @since 02/02/2015
 */
public class GUIEstatisticas extends javax.swing.JDialog {

    //Instanciando objeto para acessar o método de busca:
    private static EstatisticasServicos es = ServicosFactory.getEstatisticasServicos();

    //Objeo para receber o resultado das consultas:
    private static EstatisticasVO est;

    /**
     * Creates new form GUIEstatisticas
     */
    public GUIEstatisticas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Método para preencher as caixas de seleção:
        preencherSelecaoSecretaria();
        preencherSelecaoTecnico();

        //Método para enviar os dados:
        enviarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlestatIsticasDoSistemaEPTI = new javax.swing.JLabel();
        jPanelGeral = new javax.swing.JPanel();
        jlTotalDeComputadores = new javax.swing.JLabel();
        jlTotalDeComputadoresDados = new javax.swing.JLabel();
        jlTotalDeSecretarias = new javax.swing.JLabel();
        jlTotalDeSecretariasDados = new javax.swing.JLabel();
        jlTotalDeSetores = new javax.swing.JLabel();
        jlTotalDeSetoresDados = new javax.swing.JLabel();
        jlTotalDeUsuarios = new javax.swing.JLabel();
        jlTotalDeUsuariosDados = new javax.swing.JLabel();
        jPanelComputadores = new javax.swing.JPanel();
        jlConcluidos = new javax.swing.JLabel();
        jlConcluidosDados = new javax.swing.JLabel();
        jlEmManutencao = new javax.swing.JLabel();
        jlEmManutencaoDados = new javax.swing.JLabel();
        jlAguardandoManutencao = new javax.swing.JLabel();
        jlAguardandoManutencaoDados = new javax.swing.JLabel();
        jlDescartados = new javax.swing.JLabel();
        jlDescartadosDados = new javax.swing.JLabel();
        jPanelSecretarias = new javax.swing.JPanel();
        jlSecretaria = new javax.swing.JLabel();
        jcbSecretaria = new javax.swing.JComboBox();
        jlComputadoresDaSecretaria = new javax.swing.JLabel();
        jlComputadoresDaSecretariaDados = new javax.swing.JLabel();
        jlSetoresDaSecretaria = new javax.swing.JLabel();
        jlSetoresDaSecretariaDados = new javax.swing.JLabel();
        jlComputadoresDoSetor = new javax.swing.JLabel();
        jlComputadoresDoSetorDados = new javax.swing.JLabel();
        jlSetor = new javax.swing.JLabel();
        jcbSetor = new javax.swing.JComboBox();
        jPanelUsuarioTecnicos = new javax.swing.JPanel();
        jlTecnico = new javax.swing.JLabel();
        jcbTecnico = new javax.swing.JComboBox();
        jlDescartadosDados2 = new javax.swing.JLabel();
        jlDescartados2 = new javax.swing.JLabel();
        jlAguardandoManutencaoDados2 = new javax.swing.JLabel();
        jlAguardandoManutencao2 = new javax.swing.JLabel();
        jlEmManutencaoDados2 = new javax.swing.JLabel();
        jlEmManutencao2 = new javax.swing.JLabel();
        jlConcluidos2 = new javax.swing.JLabel();
        jlConcluidosDados2 = new javax.swing.JLabel();
        jlComputadoresDoTecnico = new javax.swing.JLabel();
        jlComputadoresDoTecnicoDados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estatísticas");

        jlestatIsticasDoSistemaEPTI.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlestatIsticasDoSistemaEPTI.setText("Estatísticas do Sistema EPTI");

        jPanelGeral.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Estatísticas gerais"));

        jlTotalDeComputadores.setText("Total de computadores:");

        jlTotalDeComputadoresDados.setText("000");

        jlTotalDeSecretarias.setText("Total de secretarias:");

        jlTotalDeSecretariasDados.setText("000");

        jlTotalDeSetores.setText("Total de setores:");

        jlTotalDeSetoresDados.setText("000");

        jlTotalDeUsuarios.setText("Total de usuários:");

        jlTotalDeUsuariosDados.setText("000");

        javax.swing.GroupLayout jPanelGeralLayout = new javax.swing.GroupLayout(jPanelGeral);
        jPanelGeral.setLayout(jPanelGeralLayout);
        jPanelGeralLayout.setHorizontalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTotalDeComputadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTotalDeComputadoresDados)
                .addGap(18, 18, 18)
                .addComponent(jlTotalDeSecretarias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTotalDeSecretariasDados)
                .addGap(18, 18, 18)
                .addComponent(jlTotalDeSetores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTotalDeSetoresDados)
                .addGap(18, 18, 18)
                .addComponent(jlTotalDeUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlTotalDeUsuariosDados)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelGeralLayout.setVerticalGroup(
            jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGeralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGeralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTotalDeComputadores)
                    .addComponent(jlTotalDeComputadoresDados)
                    .addComponent(jlTotalDeSecretarias)
                    .addComponent(jlTotalDeSecretariasDados)
                    .addComponent(jlTotalDeSetores)
                    .addComponent(jlTotalDeSetoresDados)
                    .addComponent(jlTotalDeUsuarios)
                    .addComponent(jlTotalDeUsuariosDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelComputadores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Computadores"));

        jlConcluidos.setText("Concluídos:");

        jlConcluidosDados.setText("000");

        jlEmManutencao.setText("Em manutenção:");

        jlEmManutencaoDados.setText("000");

        jlAguardandoManutencao.setText("Aguardando Manutenção:");

        jlAguardandoManutencaoDados.setText("000");

        jlDescartados.setText("Descartados:");

        jlDescartadosDados.setText("000");

        javax.swing.GroupLayout jPanelComputadoresLayout = new javax.swing.GroupLayout(jPanelComputadores);
        jPanelComputadores.setLayout(jPanelComputadoresLayout);
        jPanelComputadoresLayout.setHorizontalGroup(
            jPanelComputadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComputadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlConcluidos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlConcluidosDados)
                .addGap(40, 40, 40)
                .addComponent(jlEmManutencao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlEmManutencaoDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAguardandoManutencao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlAguardandoManutencaoDados)
                .addGap(40, 40, 40)
                .addComponent(jlDescartados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlDescartadosDados)
                .addContainerGap())
        );
        jPanelComputadoresLayout.setVerticalGroup(
            jPanelComputadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComputadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelComputadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlConcluidos)
                    .addComponent(jlConcluidosDados)
                    .addComponent(jlEmManutencao)
                    .addComponent(jlEmManutencaoDados)
                    .addComponent(jlAguardandoManutencao)
                    .addComponent(jlAguardandoManutencaoDados)
                    .addComponent(jlDescartados)
                    .addComponent(jlDescartadosDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelSecretarias.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Secretarias e setores"));

        jlSecretaria.setText("Secretaria:");

        jcbSecretaria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---" }));
        jcbSecretaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSecretariaActionPerformed(evt);
            }
        });

        jlComputadoresDaSecretaria.setText("Computadores da secretaria:");

        jlComputadoresDaSecretariaDados.setText("0");

        jlSetoresDaSecretaria.setText("Setores da secretaria:");

        jlSetoresDaSecretariaDados.setText("000");

        jlComputadoresDoSetor.setText("Computadores do setor:");

        jlComputadoresDoSetorDados.setText("0");

        jlSetor.setText("Setor:");

        jcbSetor.setEnabled(false);
        jcbSetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSetorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSecretariasLayout = new javax.swing.GroupLayout(jPanelSecretarias);
        jPanelSecretarias.setLayout(jPanelSecretariasLayout);
        jPanelSecretariasLayout.setHorizontalGroup(
            jPanelSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecretariasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSecretariasLayout.createSequentialGroup()
                        .addComponent(jlSetoresDaSecretaria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlSetoresDaSecretariaDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlComputadoresDaSecretaria))
                    .addGroup(jPanelSecretariasLayout.createSequentialGroup()
                        .addComponent(jlSecretaria)
                        .addGap(18, 18, 18)
                        .addComponent(jcbSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlSetor)))
                .addGroup(jPanelSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanelSecretariasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jcbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelSecretariasLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jlComputadoresDaSecretariaDados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlComputadoresDoSetor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlComputadoresDoSetorDados)))
                .addContainerGap())
        );
        jPanelSecretariasLayout.setVerticalGroup(
            jPanelSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSecretariasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSecretaria)
                    .addComponent(jcbSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSetor)
                    .addComponent(jcbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelSecretariasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSetoresDaSecretaria)
                    .addComponent(jlSetoresDaSecretariaDados)
                    .addComponent(jlComputadoresDoSetor)
                    .addComponent(jlComputadoresDoSetorDados)
                    .addComponent(jlComputadoresDaSecretaria)
                    .addComponent(jlComputadoresDaSecretariaDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelUsuarioTecnicos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Usuários e técnicos"));

        jlTecnico.setText("Técnico:");

        jcbTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTecnicoActionPerformed(evt);
            }
        });

        jlDescartadosDados2.setText("000");

        jlDescartados2.setText("Descartados:");

        jlAguardandoManutencaoDados2.setText("000");

        jlAguardandoManutencao2.setText("Aguardando Manutenção:");

        jlEmManutencaoDados2.setText("000");

        jlEmManutencao2.setText("Em manutenção:");

        jlConcluidos2.setText("Concluídos:");

        jlConcluidosDados2.setText("000");

        jlComputadoresDoTecnico.setText("Computadores do técnico:");

        jlComputadoresDoTecnicoDados.setText("000");

        javax.swing.GroupLayout jPanelUsuarioTecnicosLayout = new javax.swing.GroupLayout(jPanelUsuarioTecnicos);
        jPanelUsuarioTecnicos.setLayout(jPanelUsuarioTecnicosLayout);
        jPanelUsuarioTecnicosLayout.setHorizontalGroup(
            jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioTecnicosLayout.createSequentialGroup()
                .addGroup(jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUsuarioTecnicosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlTecnico)
                        .addGap(31, 31, 31)
                        .addComponent(jcbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jlComputadoresDoTecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlComputadoresDoTecnicoDados))
                    .addGroup(jPanelUsuarioTecnicosLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jlEmManutencao2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlEmManutencaoDados2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUsuarioTecnicosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jlConcluidos2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jlConcluidosDados2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                    .addComponent(jlAguardandoManutencao2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jlAguardandoManutencaoDados2)
                    .addGap(40, 40, 40)
                    .addComponent(jlDescartados2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jlDescartadosDados2)
                    .addContainerGap()))
        );
        jPanelUsuarioTecnicosLayout.setVerticalGroup(
            jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuarioTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTecnico)
                    .addComponent(jlComputadoresDoTecnico)
                    .addComponent(jlComputadoresDoTecnicoDados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmManutencao2)
                    .addComponent(jlEmManutencaoDados2))
                .addContainerGap())
            .addGroup(jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelUsuarioTecnicosLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(jPanelUsuarioTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlConcluidos2)
                        .addComponent(jlConcluidosDados2)
                        .addComponent(jlAguardandoManutencao2)
                        .addComponent(jlAguardandoManutencaoDados2)
                        .addComponent(jlDescartados2)
                        .addComponent(jlDescartadosDados2))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelComputadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSecretarias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlestatIsticasDoSistemaEPTI)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelUsuarioTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlestatIsticasDoSistemaEPTI)
                .addGap(18, 18, 18)
                .addComponent(jPanelGeral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelComputadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelSecretarias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelUsuarioTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*** Métodos da classe ****************************************************/

    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 15/01/2015
     */
    private void preencherSelecaoSecretaria(){

        try {

            //Instanciando objeto para acessar o método de busca:
            SecretariaServicos ss = ServicosFactory.getSecretariaServicos();

            //ArrayList para receber os dados da busca:
            ArrayList<SecretariaVO> secretaria;

            //Buscando secretarias:
            secretaria = ss.selecionarSecretarias();

            //Inserindo secretarias:
            secretaria.stream().forEach((secretaria1) -> {
                jcbSecretaria.addItem(secretaria1);
            });//Fim da adição das secretarias.
        } catch (SQLException e) {

            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Falha ao buscar secretarias!",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mensagem de erro.

            //Fechando janela:
            cancelar();
        }//Fecha catch.
    }//Fecha métdodo preencherSelecaoSecretaria.

    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 15/01/2015
     */
    private void preencherSelecaoSetor(){

        try {

            //Verificando se o usuário selecionou uma opção:
            if(jcbSecretaria.getSelectedIndex() > 0){

                //Removendo intes da caixa de seleção:
                jcbSetor.removeAllItems();

                //Variável para receber a secretaria selecionada:
                SecretariaVO sec;

                //Recebendo a secretaria selecionada:
                sec = (SecretariaVO)jcbSecretaria.getSelectedItem();

                //Instanciando objeto para acessar o método de busca:
                SetorServicos ss = ServicosFactory.getSetorServicos();

                //ArrayList para receber os dados da busca:
                ArrayList<SetorVO> setor;

                //Buscando setores:
                setor = ss.filtrarSetor("sec.idsecretaria", " = " + sec.getIdSecretaria());

                //Enviando total de setores:
                jlSetoresDaSecretariaDados.setText(String.valueOf(setor.size()));

                 //Inserindo secretarias:
                setor.stream().forEach((setor1) -> {
                    jcbSetor.addItem(setor1);
                });//Fim da adição dos setores.

                //Ativando caixa de seleção:
                jcbSetor.setEnabled(true);
            } else {

                //Desativando caixa de seleção:
                jcbSetor.setEnabled(false);

                //Removendo intes da caixa de seleção:
                jcbSetor.removeAllItems();

                //Enviando informação padrão para os setores da secretaria:
                jlSetoresDaSecretariaDados.setText("0");
            }//Fecha else.
        } catch (SQLException e) {

            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Falha ao buscar setores!",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mensagem de erro.

            //Fechando janela:
            cancelar();
        }//Fecha catch.
    }//Fecha método preencherSelecaoSetor.

    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 15/01/2015
     */
    private void preencherSelecaoTecnico(){

        try {

            //Criand objeto pdrão:
            UsuarioVO user = new UsuarioVO();

            //Inserindo dados:
            user.setIdUsuario(2);
            user.setNomeUsuario("Não selecionado");

            //Enviando para a caixa de seleção:
            jcbTecnico.addItem(user);

            //Instanciando objeto para acessar o método de busca:
            UsuarioServicos us = ServicosFactory.getUsuarioServicos();

            //ArrayList para receber os dados da busca:
            ArrayList<UsuarioVO> usuario;

            //Buscando técnicos:
            usuario = us.buscarTecnicos();

            //Inserindo técnicos;
            usuario.stream().forEach((usuario1) -> {
                jcbTecnico.addItem(usuario1);
            });//Fim da adição dos técnicos.
        } catch (SQLException e) {

            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Falha ao buscar técnicos!",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mensagem de erro.

            //Fechando janela:
            cancelar();
        }//Fecha catch.
    }//Fecha método preencherSelecaoTecnico.

    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 02/02/2015
     */
    private void enviarDados(){

        try {

            /*** Estatísticas gerais ******************************************/

            //Buscando estatísticas gerais:
            est = es.buscarEstatisticasGerais();

            //Enviando estatísticas para a interface:
            jlTotalDeComputadoresDados.setText(est.getTotalComputadores());
            jlTotalDeSecretariasDados.setText(est.getTotalSecretarias());
            jlTotalDeSetoresDados.setText(est.getTotalSetores());
            jlTotalDeUsuariosDados.setText(est.getTotalUsuarios());

            /*** Estatísticas computador **************************************/

            //Buscando estatísticas do computador:
            est = es.buscarEstatisticasComputador();

            //Enviando estatísticas para a interface:
            jlConcluidosDados.setText(est.getComputadoresConcluidos());
            jlEmManutencaoDados.setText(est.getComputadoresManutencao());
            jlAguardandoManutencaoDados.setText(est.getComputadoresAguardandoManutencao());
            jlDescartadosDados.setText(est.getComputadoresDescartados());
        } catch (Exception e) {

            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Erro ao enviar dados das estatísticas!",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mensagem de erro.
        }//Fecha catch.
    }//Fecha método enviarDados.

    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 02/02/2015
     */
    private void enviarEstatisticasSecretariaSetor(){

        try {

            //Objeto para receber a secretaria e o setor selecionado:
            SecretariaVO sec = (SecretariaVO) jcbSecretaria.getSelectedItem();
            SetorVO set = (SetorVO) jcbSetor.getSelectedItem();

            //Recebendo as estatísticas:
            est = es.buscarEstatisticasSecretariaSetor(sec.getIdSecretaria(), set.getIdSetor());

            /*** Enviando estatísticas ****************************************/
            
            jlComputadoresDaSecretariaDados.setText(est.getComputadoresDaSecretaria());
            jlComputadoresDoSetorDados.setText(est.getComputadoresDoSetor());
        } catch (Exception e) {


        }//Fecha catch.
    }//Fecha método enviarEstatisticasSecretariaSetor.

    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 02/02/2015
     */
    private void enviarEstatisticasTecnico(){

        try {

            //Objeto para receber o técnico selecionado:
            UsuarioVO user = (UsuarioVO)jcbTecnico.getSelectedItem();

            //Buscando estatísticas do técnico:
            est = es.buscarEstatisticasTecnico(user.getIdUsuario());

            /*** Enviando estatísticas do técnico *****************************/

            jlComputadoresDoTecnicoDados.setText(est.getComputadoresDoTecnico());
            jlConcluidosDados2.setText(est.getComputadoresConcluidosTecnico());
            jlEmManutencaoDados2.setText(est.getComputadoresManutencaoTecnico());
            jlAguardandoManutencaoDados2.setText(est.getComputadoresAguardandoManutencaoTecnico());
            jlDescartadosDados2.setText(est.getComputadoresDescartadosTecnico());
        } catch (Exception e) {

            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Erro ao enviar dados das do técnico!",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mensagem de erro.
        }//Fecha catch.
    }//Fecha método enviarEstatisticasTecnico.

    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 06/01/2015
     */
    private void cancelar(){

        //Fechando a janela:
        dispose();
    }//Fecha método cancelar.

    /*** Fim dos métodos da classe ********************************************/

    private void jcbSecretariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSecretariaActionPerformed

        //Método preencherSelecaoSetor:
        preencherSelecaoSetor();

        //Método enviarEstatisticasSecretariaSetor:
        enviarEstatisticasSecretariaSetor();
    }//GEN-LAST:event_jcbSecretariaActionPerformed

    private void jcbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSetorActionPerformed

        //Método enviarEstatisticasSecretariaSetor:
        enviarEstatisticasSecretariaSetor();
    }//GEN-LAST:event_jcbSetorActionPerformed

    private void jcbTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTecnicoActionPerformed

        //Método enviarEstatisticasTecnico:
        enviarEstatisticasTecnico();
    }//GEN-LAST:event_jcbTecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstatisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIEstatisticas dialog = new GUIEstatisticas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelComputadores;
    private javax.swing.JPanel jPanelGeral;
    private javax.swing.JPanel jPanelSecretarias;
    private javax.swing.JPanel jPanelUsuarioTecnicos;
    private javax.swing.JComboBox jcbSecretaria;
    private javax.swing.JComboBox jcbSetor;
    private javax.swing.JComboBox jcbTecnico;
    private javax.swing.JLabel jlAguardandoManutencao;
    private javax.swing.JLabel jlAguardandoManutencao2;
    private javax.swing.JLabel jlAguardandoManutencaoDados;
    private javax.swing.JLabel jlAguardandoManutencaoDados2;
    private javax.swing.JLabel jlComputadoresDaSecretaria;
    private javax.swing.JLabel jlComputadoresDaSecretariaDados;
    private javax.swing.JLabel jlComputadoresDoSetor;
    private javax.swing.JLabel jlComputadoresDoSetorDados;
    private javax.swing.JLabel jlComputadoresDoTecnico;
    private javax.swing.JLabel jlComputadoresDoTecnicoDados;
    private javax.swing.JLabel jlConcluidos;
    private javax.swing.JLabel jlConcluidos2;
    private javax.swing.JLabel jlConcluidosDados;
    private javax.swing.JLabel jlConcluidosDados2;
    private javax.swing.JLabel jlDescartados;
    private javax.swing.JLabel jlDescartados2;
    private javax.swing.JLabel jlDescartadosDados;
    private javax.swing.JLabel jlDescartadosDados2;
    private javax.swing.JLabel jlEmManutencao;
    private javax.swing.JLabel jlEmManutencao2;
    private javax.swing.JLabel jlEmManutencaoDados;
    private javax.swing.JLabel jlEmManutencaoDados2;
    private javax.swing.JLabel jlSecretaria;
    private javax.swing.JLabel jlSetor;
    private javax.swing.JLabel jlSetoresDaSecretaria;
    private javax.swing.JLabel jlSetoresDaSecretariaDados;
    private javax.swing.JLabel jlTecnico;
    private javax.swing.JLabel jlTotalDeComputadores;
    private javax.swing.JLabel jlTotalDeComputadoresDados;
    private javax.swing.JLabel jlTotalDeSecretarias;
    private javax.swing.JLabel jlTotalDeSecretariasDados;
    private javax.swing.JLabel jlTotalDeSetores;
    private javax.swing.JLabel jlTotalDeSetoresDados;
    private javax.swing.JLabel jlTotalDeUsuarios;
    private javax.swing.JLabel jlTotalDeUsuariosDados;
    private javax.swing.JLabel jlestatIsticasDoSistemaEPTI;
    // End of variables declaration//GEN-END:variables
}
