/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import utilidades.Validacao;

/**
 * @author Maikel Maciel Rönnau
 * @version 1.0
 * @since 03/02/2015
 */
public class GUIEditarBanco extends javax.swing.JDialog {

    /**
     * Creates new form GUIEditarBanco
     */
    public GUIEditarBanco(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        //Método para enviar os dados:
        enviarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jlMensagem1 = new javax.swing.JLabel();
        jlDados1 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jlEndereco = new javax.swing.JLabel();
        jlUsuario = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jlDados2 = new javax.swing.JLabel();
        jlDados3 = new javax.swing.JLabel();
        jlMensagem2 = new javax.swing.JLabel();
        jlEndereco2 = new javax.swing.JLabel();
        jtEndereco = new javax.swing.JTextField();
        jlEndereco3 = new javax.swing.JLabel();
        jtEndereco2 = new javax.swing.JTextField();
        jlUsuario2 = new javax.swing.JLabel();
        jtUsuario = new javax.swing.JTextField();
        jlSenha2 = new javax.swing.JLabel();
        jtSenha = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição do banco de dados");

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlTitulo.setText("Alterando informações do banco de dados");

        jlMensagem1.setText("Estas são as informações atuais de configuração:");

        jlDados1.setText("dados1");

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/confirmar.png"))); // NOI18N
        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });
        jbSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbSalvarKeyReleased(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jbCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbCancelarKeyPressed(evt);
            }
        });

        jlEndereco.setText("Endereço:");

        jlUsuario.setText("Usuário:");

        jlSenha.setText("Senha:");

        jlDados2.setText("dados2");

        jlDados3.setText("dados3");

        jlMensagem2.setText("Para alterar os dados preencha os campos abaixo:");

        jlEndereco2.setText("Endereço: jdbc:mysql://");

        jlEndereco3.setText(":3306/");

        jlUsuario2.setText("Usuário:");

        jlSenha2.setText("Senha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMensagem1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlEndereco)
                                .addGap(18, 18, 18)
                                .addComponent(jlDados1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlUsuario)
                                    .addComponent(jlSenha))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDados3)
                                    .addComponent(jlDados2)))))
                    .addComponent(jlMensagem2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlEndereco2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlEndereco3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlUsuario2)
                                    .addComponent(jlSenha2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtUsuario)
                                    .addComponent(jtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbCancelar)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addComponent(jlMensagem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDados1)
                    .addComponent(jlEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario)
                    .addComponent(jlDados2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha)
                    .addComponent(jlDados3))
                .addGap(25, 25, 25)
                .addComponent(jlMensagem2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndereco2)
                    .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEndereco3)
                    .addComponent(jtEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsuario2)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSenha2)
                    .addComponent(jtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*** Métodos da classe ****************************************************/
    
    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 03/02/2015
     */
    private void enviarDados(){
        
        try {
            
            //Instanciando arquivo:
            File file = new File("database_path.txt");
            
            //Verificando se o arquivo existe:
            if(file.exists()){
            
                //Instanciando o arquivo para leitura:
                Scanner scanner = new Scanner(new FileReader("database_path.txt")).useDelimiter("\\||\\n");

                //Lendo informações do banco de dados:
                String endereco = scanner.next();
                String banco = scanner.next()+scanner.next();
                String usuario = scanner.next()+scanner.next()+scanner.next();
                String senha = scanner.next();

                //Lendo informações do banco de dados:
                jlDados1.setText("jdbc:mysql://"+endereco+":3306/"+banco);
                jlDados2.setText(usuario);
                jlDados3.setText(senha);
            } else {
                
                //Verificando se o usuário deseja mesmo configurar:
                int opcao = JOptionPane.showConfirmDialog(
                                this,
                                "O arquivo de configuração não foi encontrado. Deseja criá-lo agora?",
                                "Confirmar configuração",
                                JOptionPane.YES_NO_OPTION);
                            //Fim da mensagem de confirmação.

                //Verificando a resposta do usuário:
                if (opcao == 0) {
                    
                    /*** Criando arquivo de configuração do banco de dados ********/
                
                    //Criando novo arquivo:
                    FileWriter fl = new FileWriter(new File("database_path.txt"));

                    //Escrevendo informações:
                    fl.write("localhost||epti||root||root||");

                    //Fechando arquivo:
                    fl.close();
                    
                    //Limpando campos:
                    jtEndereco.setText(null);
                    jtEndereco2.setText(null);
                    jtUsuario.setText(null);
                    jtSenha.setText(null);
                    
                    //Recorrência:
                    enviarDados();
                }//Fecha if.
            }//Fecha else.
        } catch (HeadlessException | IOException e) {
            
            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Erro ao ler informações do banco de dados! " + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mensagem de erro.
        }//Fecha catch.
    }//Fecha método enviarDados.
    
    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 03/02/2015
     */
    private void salvar(){
        
        try {
            
            //Validando dados:
            Validacao.validarDados(jtEndereco.getText().toLowerCase());
            Validacao.validarDados(jtEndereco2.getText().toLowerCase());
            Validacao.validarUsuario(jtUsuario.getText().toLowerCase());
            
            //Criando novo arquivo:
            FileWriter fl = new FileWriter(new File("database_path.txt"));
            
            //Escrevendo informações:
            fl.write(jtEndereco.getText()+"||"+jtEndereco2.getText()+"||"+jtUsuario.getText()+"||"+jtSenha.getText()+"||");
            
            //Fechando arquivo:
            fl.close();
            
            //Mensagem de confirmação:
            JOptionPane.showMessageDialog(
                this,
                "Dados salvos com sucesso!",
                "Alteração concluída",
                JOptionPane.INFORMATION_MESSAGE);
            //Fim da mensagem de confirmação.
            
            //Recorrência:
            enviarDados();
        } catch (Exception e) {
            
            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Falha ao gravar informações!"
              + "\n\n" + e.getMessage(),
                "Impossível salvar",
                JOptionPane.WARNING_MESSAGE);
            //Fim da mensagem de erro.
        }//Fecha catch.        
    }//Fecha método salvar:
    
    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 06/01/2015
     */
    private void cancelar(){
        
        //Fechando a janela:
        dispose();
    }//Fecha método cancelar.
    
    /*** Fim dos métodos da classe ********************************************/
    
    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        
        //Método salvar:
        salvar();
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbSalvarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbSalvarKeyReleased
        
        //Verificando se o usuário utilizou o teclado para selecionar a opção:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            salvar();
        }//Fecha if.
    }//GEN-LAST:event_jbSalvarKeyReleased

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        
        //Método cancelar:
        cancelar();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbCancelarKeyPressed
        
        //Verificando se o usuário utilizou o teclado para selecionar a opção:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            cancelar();
        }//Fecha if.
    }//GEN-LAST:event_jbCancelarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEditarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEditarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEditarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEditarBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUIEditarBanco dialog = new GUIEditarBanco(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JLabel jlDados1;
    private javax.swing.JLabel jlDados2;
    private javax.swing.JLabel jlDados3;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlEndereco2;
    private javax.swing.JLabel jlEndereco3;
    private javax.swing.JLabel jlMensagem1;
    private javax.swing.JLabel jlMensagem2;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlSenha2;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUsuario;
    private javax.swing.JLabel jlUsuario2;
    private javax.swing.JTextField jtEndereco;
    private javax.swing.JTextField jtEndereco2;
    private javax.swing.JTextField jtSenha;
    private javax.swing.JTextField jtUsuario;
    // End of variables declaration//GEN-END:variables
}
