
package GUI;

import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import servicos.PrimeiraUtilizacaoServicos;
import servicos.ServicosFactory;

/**
 * @author Maikel Maciel Rönnau
 * @version 1.0
 * @since 03/02/2015
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        
        //Definindo ícone:
        definirIcone();
        
        //Selecionando Look&Feel:
        selecionarLookAndFeel();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jbPrimeiraUtilizacao = new javax.swing.JButton();
        jbAlterarInformacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurador banco de dados");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Assitente de configuração de banco de dados");

        jbPrimeiraUtilizacao.setText("Configurar banco de dados para primeira utilização");
        jbPrimeiraUtilizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPrimeiraUtilizacaoActionPerformed(evt);
            }
        });
        jbPrimeiraUtilizacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbPrimeiraUtilizacaoKeyPressed(evt);
            }
        });

        jbAlterarInformacoes.setText("Alterar endereço, nome, usuário e senha do banco de dados");
        jbAlterarInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarInformacoesActionPerformed(evt);
            }
        });
        jbAlterarInformacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbAlterarInformacoesKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAlterarInformacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPrimeiraUtilizacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTitulo)
                .addGap(18, 18, 18)
                .addComponent(jbPrimeiraUtilizacao)
                .addGap(18, 18, 18)
                .addComponent(jbAlterarInformacoes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*** Métodos da classe ****************************************************/
    
    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 05/01/2015
     */
    private void selecionarLookAndFeel(){
        
        /*** Selecionando Look & Feel *****************************************/
        
        try {
            
            //Selecionando Look & Feel:
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            
            JOptionPane.showMessageDialog(
                this,
                "Erro ao inicializar interface. Procure o administrador do sistema "
              + "para resolver este problema.",
                "Erro",
                JOptionPane.ERROR);
            //Fim da mensagem de erro.
        }//Fecha catch.
        
        /*** Fim da seleção do Look & Feel ************************************/
    }//Fecha método selecionarLookAndFeel.
    
    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 12/04/2014
     */
    private void definirIcone(){
        
        //Criando objeto com a imagem:
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/icones/icone_sistema.png"));
        
        //Definindo imagem:
        setIconImage(icon.getImage());
    }//Fecha método definirIcone.
    
    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 03/02/2014
     */
    private void configurarBancoPrimeiraUtilizacao(){
        
        try {
            
            //Verificando se o usuário deseja mesmo configurar:
            int opcao = JOptionPane.showConfirmDialog(
                    this,
                    "Tem certeza que deseja configurar o banco de dados agora?"
                  + "\n\nEste configurador irá criar um arquivo de configuração que deve ser salvo"
                  + "\nna pasta \"database\" onde o sistema foi instalado, para isso execute este"
                  + "\nutilitário somente dentro da pasta indicada.\n\n",
                    "Confirmar configuração",
                    JOptionPane.YES_NO_OPTION);
                    //Fim da mensagem de confirmação.

            //Verificando a resposta do usuário:
            if (opcao == 0) {
            
                //Instanciando objeto para acessar o método de configuração:
                PrimeiraUtilizacaoServicos ps = ServicosFactory.getPrimeiraUtilizacaoServicos();

                //Configurando banco de dados:
                ps.configurarBancoPrimeiraUtilizacao();

                try {
                    
                    /*** Criando arquivo de configuração do banco de dados ********/
                
                    //Criando novo arquivo:
                    FileWriter fl = new FileWriter(new File("database_path.txt"));

                    //Escrevendo informações:
                    fl.write("localhost||epti||root||root||");

                    //Fechando arquivo:
                    fl.close();
                } catch (IOException e) {
                    
                    //Mensagem de erro:
                    JOptionPane.showMessageDialog(
                        this,
                        "Erro ao criar arquivo de configuração de banco de dados!"
                      + "\n\n" + e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                    //Fim da mesagem de erro.
                }//Fecha catch.
                
                //Mensagem de confirmação:
                JOptionPane.showMessageDialog(
                    this,
                    "Configuração concluída!"
                  + "\n\nPara o primeiro acesso utilize o usuário 'user.admin' com a senha '102030'."
                  + "\n\nNão se esqueça de trocar a senha deste usuário!",
                    "Banco de dados configurado",
                    JOptionPane.INFORMATION_MESSAGE);
            }//Fecha else.
        } catch (SQLException e) {
            
            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Erro ao configurar banco de dados para a primeira utilização!"
              + "\n\n" + e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mesagem de erro.
        }//Fecha catch.
    }//Fecha método configurarBancoPrimeiraUtilizacao.
    
    /**
     * @author Maikel Maciel Rönnau
     * @version 1.0
     * @since 03/02/2014
     */
    private void abrirGUIEdiarBanco(){
        
        try {
            
            //Instanciando objeto da classe GUIEditarBanco:
            GUIEditarBanco geb = new GUIEditarBanco(this, true);
            
            //Tornando a janela visível:
            geb.setVisible(true);
        } catch (Exception e) {
            
            //Mensagem de erro:
            JOptionPane.showMessageDialog(
                this,
                "Erro ao abrir a edição do banco de dados!",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
            //Fim da mesagem de erro.
        }//Fecha catch.
    }//Fecha método abrirGUIEdiarBanco.
    
    /*** Fim dos métodos da classe ********************************************/
    
    private void jbPrimeiraUtilizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPrimeiraUtilizacaoActionPerformed

        //Método configurarBancoPrimeiraUtilizacao:
        configurarBancoPrimeiraUtilizacao();
    }//GEN-LAST:event_jbPrimeiraUtilizacaoActionPerformed

    private void jbPrimeiraUtilizacaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbPrimeiraUtilizacaoKeyPressed
        
        //Verificando se o usuário utilizou o teclado para selecionar a opção:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            configurarBancoPrimeiraUtilizacao();
        }//Fecha if.
    }//GEN-LAST:event_jbPrimeiraUtilizacaoKeyPressed

    private void jbAlterarInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarInformacoesActionPerformed
        
        //Método abrirGUIEdiarBanco:
        abrirGUIEdiarBanco();
    }//GEN-LAST:event_jbAlterarInformacoesActionPerformed

    private void jbAlterarInformacoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbAlterarInformacoesKeyPressed
        
        //Verificando se o usuário utilizou o teclado para selecionar a opção:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            abrirGUIEdiarBanco();
        }//Fecha if.
    }//GEN-LAST:event_jbAlterarInformacoesKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAlterarInformacoes;
    private javax.swing.JButton jbPrimeiraUtilizacao;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
